apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: smart-window-microservice
  namespace: default
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - image: crpi-cn1s409pxj9e0zxn.cn-hangzhou.personal.cr.aliyuncs.com/smartintent/smartwindow:v1
          ports:
            - containerPort: 3000
