apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: intent-server
  namespace: default
spec:
  template:
    spec:
      containers:
        # - image: docker.io/wangjiayue123/intent-server:v7
        # - image: docker.io/cczhh/intent-server:v1
        - image: crpi-cn1s409pxj9e0zxn.cn-hangzhou.personal.cr.aliyuncs.com/smartintent/intent-server:qwen-v6
        # - image: intent-server:local
        #   imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
