apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recorder-service
  namespace: default
spec:
  template:
    spec:
      containers:
        # - image: shidina/recorder-service:v1
        # - image: docker.io/cczhh/voiceinterface:voicefix1
        - image: docker.io/cczhh/voiceinterface:voicefix2
          ports:
            - containerPort: 5001